spring.datasource.postgres.jdbc-url=jdbc:postgresql://localhost:5433/data_migration
spring.datasource.postgres.username=postgres
spring.datasource.postgres.password=mypassword
spring.datasource.postgres.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.datasource.sqlserver.jdbc-url=jdbc:sqlserver://localhost:1433;databaseName=tempdb;trustServerCertificate=true;
spring.datasource.sqlserver.username=sa
spring.datasource.sqlserver.password=yourStrong(!)Password
spring.datasource.sqlserver.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver